version: '3.8'

services:
  backend:
    build:
      context: ./entrusting-client/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./entrusting-client/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    # React 앱에서 백엔드 API URL을 /api로 사용하도록 .env 파일 설정
    environment:
      VITE_BACKEND_API_URL: /api
    # React 앱에서 백엔드 API URL을 /api로 사용하도록 .env 파일 설정
    environment:
      VITE_BACKEND_API_URL: /api
